scan_timeout = 60
add_newline = false

[line_break]
disabled = true

[directory]
style = "bold blue"

[cmd_duration]
format = " took [ $duration]($style) "
style = "bold fg:yellow"
min_time = 500

[status]
disabled = false
format = "[$symbol $status]($style) "
not_found_symbol = ""
not_executable_symbol = ""
sigint_symbol = "ﭦ"
map_symbol = true

[git_branch]
format = "-> [$symbol$branch]($style) "
style = "bold fg:mauve"
symbol = " "

[git_status]
format = '[$all_status$ahead_behind ]($style)'
style = "fg:text bg:pink"

[package]
format = "[$symbol$version]($style) "
symbol = "󰏗 "

[python]
disabled = false
format = "[$symbol$pyenv_prefix($version)( $virtualenv)](fg:peach)"
symbol = " "
version_format = "$raw"

[nodejs]
format = "[$symbol($version )]($style)"
symbol = " "

[php]
format = "[$symbol($version )]($style)"
symbol = " "

[java]
format = "[${symbol}(${version} )]($style)"
symbol = " "

[rust]
format = "[$symbol($version )]($style)"
symbol = "󱘗 "

[golang]
format = "[$symbol($version )]($style)"
symbol = " "
