[aliases]
mononoki = "Mononoki Nerd Font Mono"
ubuntumono = "UbuntuMono Nerd Font"
hack = "Hack Nerd Font Mono"
firacode = "FiraCode Nerd Font Mono"
agave = "Agave Nerd Font Mono"
caskaydiacove = "CaskaydiaCove Nerd Font Mono"
jetbrains = "JetBrainsMono Nerd Font Mono"
